addons/sourcemod/configs/zombie_riot/waves_alt.cfg, addons/sourcemod/scripting/zombie_riot.sp, addons/sourcemod/scripting/zombie_riot/npc/alt/npc_alt_medic_berserker.sp, addons/sourcemod/scripting/zombie_riot/npc_stats.sp
alt waves new npc, includes the zombie_riot.sp, npc_stats.sp, and cfg update for the npc
=> Alt waves new npc

addons/sourcemod/translations/zombieriot.phrases.bob.txt, addons/sourcemod/translations/zombieriot.phrases.txt, addons/sourcemod/translations/zombieriot.phrases.weapons.txt
- Added . (dots) at the end of some bob strings plus fixed some typo there.
- Fixed line break code at russian string.
- Removed duplicated string ```"MAX BARRICADES OUT CURRENTLY"```.
- Fixed typos.
- Obviously updated outdated russian translation.
=> Russian translation update and few string fixes

addons/sourcemod/configs/zombie_riot/weapons.cfg, addons/sourcemod/scripting/zombie_riot.sp, addons/sourcemod/scripting/zombie_riot/custom/weapon_zeroknife.sp
Removed broken stuff that didn't worked either way (Heal 1hp on hit on wrath, speed modifier rage being dead and waste)
Added Pap ver and better then the default one which got nerfed heavily.
please someone else test it then just 2 AAAA
=> New Pap Ver of Zerofuse knife

addons/sourcemod/configs/zombie_riot/weapons.cfg
Buffed Zerofuse Knife Damage
Added a Pap ver for Kahml Fists (might need a slight change again)
=> Slight buff and pap

addons/sourcemod/configs/zombie_riot/weapons.cfg, addons/sourcemod/scripting/zombie_riot/custom/weapon_zeroknife.sp
Added another pap ver added res to all melees so it doesn't feel deadweight to use.
Made first knife use Defence Rage that wasn't used at all in the .sp
Made Defence Cooldown back to 80s since it was 15s?
You can yell at me later
=> Once again zeroknife

addons/sourcemod/configs/zombie_riot/weapons.cfg
=> Survival blade

addons/sourcemod/configs/zombie_riot/weapons.cfg
Buffed pap Flamethrower slightly increased it's price a bit
Added another pap varient for Fire Axe
=> Flamethrower and Fire Axe

addons/sourcemod/configs/zombie_riot/weapons.cfg, addons/sourcemod/scripting/zombie_riot.sp, addons/sourcemod/scripting/zombie_riot/custom/weapon_cspyknife.sp, addons/sourcemod/scripting/zombie_riot/npcs.sp
Deals barely any backstab dmg main, intend is to butterknife the enemy to death
Has an rng pool every 1s to use and every effect is 0.33s-0.88s long.
=> Corrupted Spy Knife Wannabe ver

addons/sourcemod/translations/zombieriot.phrases.txt
this will take a while to finish, so be patient, that is... if i don't procrastinate
=> PT-BR translation

addons/sourcemod/configs/zombie_riot/weapons.cfg, addons/sourcemod/scripting/zombie_riot/custom/weapon_cspyknife.sp
Second Pap:
Fixed Attack Speed Bonus Not working after getting the rng one.
Nerfed it a bit via speed rng.
Nerfed it's Dmg Bonus on rng.
Slowness is more noticable on this ver.
Third Pap:
Added a lot more dmg varients and such might need more later on.
=> New Pap Knife, Fixed Second one

addons/sourcemod/scripting/zombie_riot/custom/weapon_zeroknife.sp
Not much of a fix just a simplify for solace *i hope it does*
=> Updated weapon_zerofuse.sp

addons/sourcemod/configs/zombie_riot/weapons.cfg
Noticed that it isn't that good on later waves for a 10k pap.
Buffed it's damage from 17.02 -> 20.55
Increased it's attack speed by 2%
=> Buffed 3 Pap of Knife

addons/sourcemod/translations/zombieriot.phrases.txt, addons/sourcemod/translations/zombieriot.phrases.weapons.txt
Weapon translation is not working
=> Updated some Chinese translations

addons/sourcemod/translations/zombieriot.phrases.txt, addons/sourcemod/translations/zombieriot.phrases.weapons.txt
The "Ranged Upgrades" description doesn't seem to work
=> Fixing Chinese

addons/sourcemod/scripting/zombie_riot/npc/raidmode_bosses/npc_blitzkrieg.sp
also more updates soon:tm:, alongside the altwaves stage 3 overhaul whenever I have time
=> oh look, blitz minnion billion's of hp no more

addons/sourcemod/translations/zombieriot.phrases.txt, addons/sourcemod/translations/zombieriot.phrases.weapons.description.txt, addons/sourcemod/translations/zombieriot.phrases.weapons.txt
=> More translations

addons/sourcemod/scripting/zombie_riot/custom/wand/weapon_lantean_wand.sp
=> one tiny tiny change

addons/sourcemod/configs/zombie_riot/weapons.cfg, addons/sourcemod/scripting/zombie_riot/custom/weapon_zeroknife.sp
less damage on final 
and less wrath attack speed
=> Nerf zerofuse knife

addons/sourcemod/configs/zombie_riot/weapons.cfg, addons/sourcemod/scripting/zombie_riot/custom/weapon_board.sp, addons/sourcemod/translations/zombieriot.phrases.weapons.description.txt
=> Buffs and nerfs to shield

addons/sourcemod/configs/zombie_riot/weapons.cfg, addons/sourcemod/scripting/zombie_riot/custom/weapon_board.sp, addons/sourcemod/translations/zombieriot.phrases.weapons.description.txt
made it more self-sufficient, worse with medics and overall better for single-target tanking rather than crowd-tanking
I have no way of knowing whether or not the medic healing penalty actually works until it gets tested in-game so heres a quick prayer to the omnissiah i didnt screw it up
=> shield changes once again

addons/sourcemod/configs/zombie_riot/weapons.cfg, addons/sourcemod/scripting/shared/npcs.sp, addons/sourcemod/scripting/zombie_riot/custom/weapon_hazard.sp, addons/sourcemod/scripting/zombie_riot/zr_core.sp, addons/sourcemod/translations/zombieriot.phrases.weapons.description.txt
True fact: 99% of all gamblers hit before hitting it big
=> funny tocksick weapon

addons/sourcemod/configs/zombie_riot/weapons.cfg, addons/sourcemod/scripting/zombie_riot/custom/weapon_casino.sp, addons/sourcemod/translations/zombieriot.phrases.weapons.description.txt
i swear attack speed is a deadly sin
=> Casino changes

addons/sourcemod/configs/zombie_riot/weapons.cfg, addons/sourcemod/scripting/shared/store.sp, addons/sourcemod/scripting/zombie_riot/custom/weapon_board.sp, addons/sourcemod/translations/zombieriot.phrases.weapons.description.txt
added
-healing after not taking damage
-interruption for said healing (taking damage and switching weps) 
-few price tweaks
-rookie and cudgel dont slow you down nor give you hp anymore 
-yea
=> board and shield changes

addons/sourcemod/scripting/shared/killfeed.sp
Fixes kill feed being backed up especially on modes like bloons.
=> Fix Killfeed Being Delayed

addons/sourcemod/configs/zombie_riot/weapons.cfg, addons/sourcemod/scripting/shared/custom_melee_logic.sp, addons/sourcemod/scripting/shared/wand_projectile.sp, addons/sourcemod/scripting/zombie_riot/custom/kit_blitzkrieg.sp, addons/sourcemod/translations/zombieriot.phrases.weapons.description.txt, addons/sourcemod/translations/zombieriot.phrases.weapons.txt
github compiler is angry at something that it shouldn't be, it does exist
=> Add new kit

addons/sourcemod/configs/zombie_riot/weapons.cfg, addons/sourcemod/scripting/shared/core.sp, addons/sourcemod/scripting/shared/custom_melee_logic.sp, addons/sourcemod/scripting/shared/npc_stats.sp, addons/sourcemod/scripting/shared/npcs.sp, addons/sourcemod/scripting/shared/sdkhooks.sp, addons/sourcemod/scripting/shared/store.sp, addons/sourcemod/scripting/zombie_riot/custom/weapon_rapier.sp, addons/sourcemod/scripting/zombie_riot/zr_core.sp, addons/sourcemod/translations/zombieriot.phrases.weapons.description.txt
Headshots are the only thing missing lol
also buffed casino dmg because it was ass before
=> Rapier (Without Headshots)

addons/sourcemod/scripting/zombie_riot/custom/weapon_rapier.sp, addons/sourcemod/translations/zombieriot.phrases.weapons.description.txt
(raidboss buff, 2nd pap now has a purpose, duel buff, fixed bugs for rapier)
=> this cuh so intelligent

addons/sourcemod/scripting/shared/core.sp, addons/sourcemod/scripting/shared/npc_stats.sp, addons/sourcemod/scripting/shared/npcs.sp, addons/sourcemod/scripting/shared/stocks.sp, addons/sourcemod/scripting/shared/stocks_override.sp, addons/sourcemod/scripting/smrts.sp, addons/sourcemod/scripting/zombie_riot/npc/ally/npc_barrack.sp, addons/sourcemod/scripting/zombie_riot/smrts.sp, addons/sourcemod/scripting/zombie_riot/zr_core.sp
=> RTS Experiment

addons/sourcemod/configs/zombie_riot/weapons.cfg, addons/sourcemod/scripting/zombie_riot/custom/weapon_rapier.sp, addons/sourcemod/translations/zombieriot.phrases.weapons.description.txt
=> Tapir! :+1:

addons/sourcemod/scripting/zombie_riot/custom/wand/weapon_wand_skulls.sp
Fixes an invalid entity error.
=> Fix Skull Servants Error

addons/sourcemod/configs/zombie_riot/weapons.cfg, addons/sourcemod/scripting/zombie_riot/custom/weapon_charged_handgun.sp
A new path and and a final pap for the path 1
=> IEM Launcher upgrade

addons/sourcemod/configs/zombie_riot/weapons.cfg
=> I learnt economy!

addons/sourcemod/configs/zombie_riot/weapons.cfg, addons/sourcemod/scripting/shared/store.sp, addons/sourcemod/scripting/zombie_riot/custom/wand/weapon_dimension_ripper.sp, addons/sourcemod/scripting/zombie_riot/zr_core.sp, addons/sourcemod/translations/zombieriot.phrases.weapons.description.txt
=> DImension Ripper

addons/sourcemod/configs/zombie_riot/weapons.cfg, addons/sourcemod/scripting/shared/npcs.sp, addons/sourcemod/scripting/zombie_riot/custom/wand/weapon_dimension_ripper.sp
some buffs & particle change & pap fix
=> dimension tweak

addons/sourcemod/scripting/zombie_riot/custom/wand/weapon_dimension_ripper.sp
Heavily buffed allies, nerfed the amount of charges required
=> Dimension tweaking

addons/sourcemod/configs/zombie_riot/weapons.cfg, addons/sourcemod/scripting/shared/stocks.sp, addons/sourcemod/scripting/shared/store.sp, addons/sourcemod/scripting/zombie_riot/custom/weapon_hell_hoe.sp
also fix junker healing and fire rate issues
=> of course I forgot to update the stock

addons/sourcemod/configs/zombie_riot/weapons.cfg, addons/sourcemod/scripting/zombie_riot/custom/wand/weapon_dimension_ripper.sp
=> Dimension balance

addons/sourcemod/configs/zombie_riot/weapons.cfg, addons/sourcemod/scripting/zombie_riot/custom/wand/weapon_dimension_ripper.sp
=> Dimension_Newpap

addons/sourcemod/configs/zombie_riot/weapons.cfg, addons/sourcemod/scripting/zombie_riot/custom/wand/weapon_ludo.sp
=> for some reason the cost change didnt go through???

addons/sourcemod/scripting/zombie_riot/custom/wand/weapon_dimension_ripper.sp
added Brawler, changed seaborns to nourished, added xeno kamikaze demo, changed Khazaan to INABDIL, and minor stat changes to npcs.
=> Dimension unitbuff

addons/sourcemod/configs/zombie_riot/weapons.cfg, addons/sourcemod/scripting/zombie_riot/custom/wand/weapon_dimension_ripper.sp, addons/sourcemod/translations/zombieriot.phrases.weapons.description.txt
=> Dimension Fun

addons/sourcemod/configs/zombie_riot/weapons.cfg, addons/sourcemod/scripting/zombie_riot/custom/weapon_deagle_west.sp
1. Model update for west revolver 
2. Red Blade resize 
3. Added Crouch Button in order to activate R ability in west revolver 
4. slightly buffed messenger's launcher
=> Small changes

waves_insanity.cfg
Gave people more money in the early waves and nerfed some starting waves
=> hisworld nerfs

addons/sourcemod/configs/zombie_riot/weapons.cfg
=> FIXED INSANE FALLOFF

addons/sourcemod/configs/zombie_riot/weapons.cfg, addons/sourcemod/scripting/shared/damage.sp, addons/sourcemod/scripting/shared/events.sp, addons/sourcemod/scripting/zombie_riot/custom/weapon_flametail.sp, addons/sourcemod/scripting/zombie_riot/custom/weapon_saga.sp, addons/sourcemod/scripting/zombie_riot/store.sp, addons/sourcemod/scripting/zombie_riot/zr_core.sp, addons/sourcemod/translations/zombieriot.phrases.weapons.description.txt, addons/sourcemod/translations/zombieriot.phrases.weapons.txt
=> New Warpaints

addons/sourcemod/scripting/zombie_riot/npc/ally/combine_barracks/npc_barrack_combine_collos.sp, addons/sourcemod/scripting/zombie_riot/npc/ally/combine_barracks/npc_barrack_combine_swordsman.sp
=> barracks combine fix

addons/sourcemod/scripting/zombie_riot/npc/ally/combine_barracks/npc_barrack_combine_giant_ddt.sp, addons/sourcemod/scripting/zombie_riot/npc/ally/combine_barracks/npc_barrack_combine_pistol.sp, addons/sourcemod/scripting/zombie_riot/npc/ally/combine_barracks/npc_barrack_combine_shotgunner.sp, addons/sourcemod/scripting/zombie_riot/npc/ally/combine_barracks/npc_barrack_combine_smg.sp, addons/sourcemod/scripting/zombie_riot/npc/ally/combine_barracks/npc_barrack_combine_sniper.sp, addons/sourcemod/scripting/zombie_riot/npc/ally/combine_barracks/npc_barrack_combine_super.sp
=> barracks change

addons/sourcemod/scripting/zombie_riot/npc/ally/combine_barracks/npc_barrack_combine_ar2.sp, addons/sourcemod/scripting/zombie_riot/npc/ally/combine_barracks/npc_barrack_combine_collos.sp, addons/sourcemod/scripting/zombie_riot/npc/ally/combine_barracks/npc_barrack_combine_commander.sp, addons/sourcemod/scripting/zombie_riot/npc/ally/combine_barracks/npc_barrack_combine_elite.sp, addons/sourcemod/scripting/zombie_riot/npc/ally/combine_barracks/npc_barrack_combine_pistol.sp, addons/sourcemod/scripting/zombie_riot/npc/ally/combine_barracks/npc_barrack_combine_shotgunner.sp, addons/sourcemod/scripting/zombie_riot/npc/ally/combine_barracks/npc_barrack_combine_smg.sp, addons/sourcemod/scripting/zombie_riot/npc/ally/combine_barracks/npc_barrack_combine_sniper.sp, addons/sourcemod/scripting/zombie_riot/npc/ally/combine_barracks/npc_barrack_combine_swordsman.sp
=> Guln's barracks changes

addons/sourcemod/scripting/zombie_riot/npc/ally/iberia_barracks/npc_barrack_boomstick.sp, addons/sourcemod/scripting/zombie_riot/npc/ally/iberia_barracks/npc_barrack_elite_gunner.sp, addons/sourcemod/scripting/zombie_riot/npc/ally/iberia_barracks/npc_barrack_guards.sp, addons/sourcemod/scripting/zombie_riot/npc/ally/iberia_barracks/npc_barrack_gunner.sp, addons/sourcemod/scripting/zombie_riot/npc/ally/iberia_barracks/npc_barrack_healer.sp, addons/sourcemod/scripting/zombie_riot/npc/ally/iberia_barracks/npc_barrack_healtanker.sp, addons/sourcemod/scripting/zombie_riot/npc/ally/iberia_barracks/npc_barrack_lighthouse_guardian.sp, addons/sourcemod/scripting/zombie_riot/npc/ally/iberia_barracks/npc_barrack_rocketeer.sp, addons/sourcemod/scripting/zombie_riot/npc/ally/iberia_barracks/npc_barrack_runner.sp, addons/sourcemod/scripting/zombie_riot/npc/ally/iberia_barracks/npc_barrack_tanker.sp, addons/sourcemod/scripting/zombie_riot/object/obj_barracks.sp
=> Iberian buff

addons/sourcemod/translations/zombieriot.phrases.item.gift.desc.txt, addons/sourcemod/translations/zombieriot.phrases.txt, addons/sourcemod/translations/zombieriot.phrases.zombienames.txt
=> encyclopedia for raids

addons/sourcemod/translations/zombieriot.phrases.item.gift.desc.txt, addons/sourcemod/translations/zombieriot.phrases.txt, addons/sourcemod/translations/zombieriot.phrases.zombienames.txt
=> FIxed stella desc as well as desc going after hers and possibly tried to fix sensal desc being cutted off

addons/sourcemod/configs/zombie_riot/weapons.cfg
=> Messenger's launcher buff

addons/sourcemod/configs/zombie_riot/weapons.cfg, addons/sourcemod/scripting/shared/core.sp, addons/sourcemod/scripting/shared/damage.sp, addons/sourcemod/scripting/shared/global_arrays.sp, addons/sourcemod/scripting/shared/npcs.sp, addons/sourcemod/scripting/zombie_riot/custom/weapon_casino.sp, addons/sourcemod/translations/zombieriot.phrases.weapons.description.txt
Casino changes
buffs and jackpot still need their tweaks
please do not mess up anything mister code i beg
=> Hopefully this works

addons/sourcemod/configs/zombie_riot/challenges/freeplay/advanced.cfg, addons/sourcemod/scripting/zombie_riot/freeplay.sp
Freeplay Changes:
Skull changes:
+ The Melee/Ranged skulls now give 20%/25% vulnerability instead of 10%/15%
+ The Friendly units skull now divides ally HP by 5 instead of 10
= Current extra skulls are instead displayed as "Current skull count" now
+ Added a special freeplay event with a 2% chance of activating on each setup...
This special event overrides the skull selection.
Other:
+ Players should start w60 with 35 extra ammo supplies now
+ The Ruina Valiant should spawn more often (should spawn 3 too)
=> More freeplay changes!!!!1!!!

addons/sourcemod/scripting/zombie_riot/custom/weapon_casino.sp
nerfed the buffs
bonus cash moved to deadshot daquiri
why am i writing this this will be in zombe-riot updates???
=> casino nerf

addons/sourcemod/scripting/zombie_riot/freeplay.sp, addons/sourcemod/translations/zombieriot.phrases.status_effects.txt
+ + Fixed Freeplay crashing at the first skull
+ + The new temporary buff skull that lasts 10 seconds is now permanent instead
=> Freeplay crash fix

addons/sourcemod/configs/zombie_riot/challenges/freeplay/advanced.cfg, addons/sourcemod/configs/zombie_riot/challenges/freeplay/vote.cfg, addons/sourcemod/scripting/zombie_riot/freeplay.sp, addons/sourcemod/scripting/zombie_riot/waves.sp, addons/sourcemod/translations/zombieriot.phrases.status_effects.txt, addons/sourcemod/translations/zombieriot.phrases.txt
Freeplay Changes:
Skulls:
+ Reduced SUPER Miniboss damage by 25%
+ HEAVILY reduced SUPER Miniboss HP (overall by 35%, base by around half)
sorry, i went way too overboard lmao
Other:
+ Theocracy and Adiantum no longer have extra freeplay speed, and reduced their extra freeplay damage from 4.5x to 3.5x
+ Changed the Freeplay w60 win voting prompt by HUD info that displays brief information about Freeplay
+ With the above changed, fixed a bug where you couldn't open the shop in Freeplay after beating w60
=> More freeplay stuff

addons/sourcemod/configs/zombie_riot/weapons.cfg, addons/sourcemod/scripting/shared/core.sp, addons/sourcemod/scripting/shared/custom/joke_medigun_mod_drain_health.sp, addons/sourcemod/scripting/shared/global_arrays.sp, addons/sourcemod/scripting/shared/sdkhooks.sp, addons/sourcemod/scripting/shared/status_effects.sp, addons/sourcemod/scripting/shared/stocks.sp, addons/sourcemod/scripting/zombie_riot/custom/m3_abilities.sp, addons/sourcemod/scripting/zombie_riot/custom/weapon_kritzkrieg.sp, addons/sourcemod/scripting/zombie_riot/music.sp, addons/sourcemod/scripting/zombie_riot/store.sp, addons/sourcemod/scripting/zombie_riot/waves.sp, addons/sourcemod/scripting/zombie_riot/zr_core.sp, addons/sourcemod/translations/zombieriot.phrases.status_effects.txt, addons/sourcemod/translations/zombieriot.phrases.txt, addons/sourcemod/translations/zombieriot.phrases.weapons.description.txt, addons/sourcemod/translations/zombieriot.phrases.weapons.txt
```diff
Add M3 Ability
Reinforce:
+A device that revives a random dead teammate, recharging through healing.
- The maximum charge increases with the amount of healing rate.
Reconstructive Teleporter:
+Teleports barrack units to you, granting overheal and high resistance for 1 second.
Add New Medigun pap
Overclocking Medigun: <- I think change name lol
= Uber charge is crit boost
+ 1.5x damage buff to healing target
+ 1.2x attack speed buff to healing target
+ Grants quick mana recovery to the target of healing
- Ubercharge Rate -50%
- Uber Duration -2s
```
=> New something

addons/sourcemod/configs/zombie_riot/weapons.cfg, addons/sourcemod/scripting/shared/custom_melee_logic.sp, addons/sourcemod/scripting/zombie_riot/custom/weapon_board.sp, addons/sourcemod/scripting/zombie_riot/custom/weapon_rapier.sp, addons/sourcemod/translations/zombieriot.phrases.weapons.description.txt
Board got a slight rework and overall improvements Rapier got slight improvements (duel, reliance on headshots, slight dmg in early paps)
=> board and rapier changes

addons/sourcemod/scripting/zombie_riot/elemental.sp
Something to counteract resistances and so, and for overdmg to not be THAT huge
=> it could be lupus?

README.md, addons/sourcemod/gamedata/zombie_riot.txt, addons/sourcemod/scripting/shared/core.sp, addons/sourcemod/scripting/shared/dhooks.sp, addons/sourcemod/scripting/zombie_riot/npc/ally/npc_allied_kahml_afterimage.sp
Ditch dhook as its broken on linux and causes wierd corruptions or something that makes random things not collide.
=> Linux fix 

addons/sourcemod/scripting/zombie_riot/npc/normal/npc_spy_half_cloacked_main.sp, addons/sourcemod/scripting/zombie_riot/npc/xeno/npc_xeno_spy_half_cloacked_main.sp
We handled them a bit differently from one another
=> Fix xeno half cloaked spy being slightly laggier than normal half cloaked spy

addons/sourcemod/configs/zombie_riot/deepforest/finalboss_dlc_4.cfg, addons/sourcemod/configs/zombie_riot/giftitems.cfg, addons/sourcemod/configs/zombie_riot/maps/zr_deepforest.cfg, addons/sourcemod/configs/zombie_riot/maps/zr_integratedstrategies.cfg, addons/sourcemod/configs/zombie_riot/weapons.cfg, addons/sourcemod/scripting/zombie_riot/npc/rogue/chaos_expansion/npc_lelouch.sp, addons/sourcemod/translations/zombieriot.phrases.rogue.paradox.txt
typo fixes (also change rogue2 end4 trophy description a bit teehee)
=> it's "curtain" without an O!!!

addons/sourcemod/translations/zombieriot.phrases.rogue.paradox.txt, addons/sourcemod/translations/zombieriot.phrases.rogue.txt
fixes inconsistencies and other gramatical errors for the rogue gamemode
=> Update Rogue.txt and Rogue.paradox.txt to make them more consistent
